name: Lint and test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Zig
        uses: korandoru/setup-zig@v1
        with:
          zig-version: 0.16.0

      - name: Display zig compiler version
        run: zig version

      - name: Build
        run: zig build

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Zig
        uses: korandoru/setup-zig@v1
        with:
          zig-version: 0.16.0

      - name: Lint
        run: zig fmt --check src/*.zig

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Zig
        uses: korandoru/setup-zig@v1
        with:
          zig-version: 0.16.0

      - name: Cache the vectors submodule
        id: vectors
        uses: actions/cache@v4
        with:
          path: |
            ethereum-tests
            .git/modules/ethereum-tests
          key: ethereum-tests

      - name: Sync the vectors submodule
        if: steps.vectors.outputs.cache-hit != 'true'
        run: git submodule update --init --depth 1 --recursive ethereum-tests

      - name: Test
        run: zig build test --summary all

  test-be:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Zig
        uses: korandoru/setup-zig@v1
        with:
          zig-version: 0.16.0

      - name: Cache the vectors submodule
        id: vectors
        uses: actions/cache@v4
        with:
          path: |
            ethereum-tests
            .git/modules/ethereum-tests
          key: ethereum-tests

      - name: Sync the vectors submodule
        if: steps.vectors.outputs.cache-hit != 'true'
        run: git submodule update --init --depth 1 --recursive ethereum-tests

      - name: Test
        run: zig build test --summary all -fqemu -Dtarget=mips64-linux
